--
-- DATABASE
--
create database DEV_POC_SPRING_SECURITY_DATABASE;

--
-- TABLE: POC_SPRING_SECURITY_USER
--
CREATE TABLE DEV_POC_SPRING_SECURITY_DATABASE.POC_SPRING_SECURITY_USER
(
    ID_USER INT(9) auto_increment primary key NOT NULL,
    LOGIN_USER VARCHAR(255) NOT NULL,
    PASSWORD_USER VARCHAR(255) NOT null,
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- TABLE: POC_SPRING_SECURITY_ROLE
--
CREATE TABLE DEV_POC_SPRING_SECURITY_DATABASE.POC_SPRING_SECURITY_ROLE
(
    ID_ROLE INT(9) auto_increment primary key NOT NULL,
    CODE_ROLE VARCHAR(255) NOT NULL,
    DESCRIPTION_ROLE VARCHAR(255) NOT NULL,
    NAME_ROLE VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- TABLE: POC_SPRING_SECURITY_REL_USER_ROLE
--
CREATE TABLE DEV_POC_SPRING_SECURITY_DATABASE.POC_SPRING_SECURITY_REL_USER_ROLE
(
    ID_REL_USER_ROLE INT(9) auto_increment primary key NOT NULL,
    ID_USER INT(9) NOT NULL,
    ID_ROLE INT(9) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
--