server.port=8081
server.servlet.context-path=/api/v1
server.servlet.session.timeout=10
server.error.include-exception=false
server.error.include-stacktrace=never
server.error.whitelabel.enabled=true

spring.application.name=poc-person-services

spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=10000
spring.datasource.hikari.connectionTimeout=250
spring.datasource.hikari.maxLifetime=600000
spring.datasource.url=jdbc:mariadb://localhost:3306/poc_person_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.url=jdbc:mariadb://mariadb:3306/poc-person-db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=dev_poc
spring.datasource.password=w83y4LX6OiUB
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.integration.envers.enabled=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.liquibase.enabled=true
spring.mvc.throw-exception-if-no-handler-found=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
spring.sql.init.encoding=UTF-8
spring.web.resources.add-mappings=false

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=debug
logging.level.org.hibernate.SQL=info
logging.level.org.hibernate.type=WARN
logging.level.org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod=debug
logging.level..=error
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n)

security.jwt.expiration-time=3600000
security.jwt.header=Authorization
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

spring.security.user.name=admin
spring.security.user.password=12345678

# CORS
cors.allowed.origins=http://localhost:4200

#Authentication Microservices
auth.service.url=http://localhost:8080/api/v1

