version: "3.8"

services:

  mariadb:
    container_name: poc-person-database
    image: mariadb:10.4
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_DATABASE: poc_person_db
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: dba_user
      MARIADB_PASSWORD: nMo9WdE(;kyOVEXY
    volumes:
      - db:/var/lib/mysql

  backend:
    container_name: poc-person-services
    depends_on:
      - mariadb
    restart: on-failure
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_USER=dba_user
      - DATABASE_PASSWORD=nMo9WdE(;kyOVEXY
      - DATABASE_NAME=poc_person_db
      - DATABASE_PORT=3306
    build: .
    ports:
      - 8081:8081
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: