--
-- DATABASE
--
create database DEV_POC_SPRING_CASCADE_DATABASE;

--
-- TABLE: POC_SPRING_CASCADE_PERSON
--
CREATE TABLE DEV_POC_SPRING_CASCADE_DATABASE.POC_SPRING_CASCADE_PERSON
(
    ID_PERSON INT(9) auto_increment primary key NOT NULL,
    NAME_PERSON VARCHAR(255) NOT NULL,
    AGE_PERSON VARCHAR(255) NOT NULL,
    HEIGHT_PERSON VARCHAR (255) NOT NULL,
    WEIGHT_PERSON VARCHAR (255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- SEQUENCE: SEQ_POC_SPRING_CASCADE_PERSON
--
CREATE SEQUENCE DEV_POC_SPRING_CASCADE_DATABASE.SEQ_POC_SPRING_CASCADE_PERSON
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
NOCACHE
--  NOORDER
;

--
-- TABLE: POC_SPRING_CASCADE_CONTACT
--
CREATE TABLE DEV_POC_SPRING_CASCADE_DATABASE.POC_SPRING_CASCADE_CONTACT
(
    ID_CONTACT INT(9) auto_increment primary key NOT NULL,
    ID_TYPE_CONTACT INT(9) NOT NULL,
    CONTACT_CONTACT VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- SEQUENCE: SEQ_POC_SPRING_CASCADE_CONTACT
--
CREATE SEQUENCE DEV_POC_SPRING_CASCADE_DATABASE.SEQ_POC_SPRING_CASCADE_CONTACT
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
NOCACHE
--  NOORDER
;

--
-- TABLE: POC_SPRING_CASCADE_REL_PERSON_CONTACT
--
CREATE TABLE DEV_POC_SPRING_CASCADE_DATABASE.POC_SPRING_CASCADE_REL_PERSON_CONTACT
(
    ID_REL_PERSON_CONTACT INT(9) auto_increment primary key NOT NULL,
    ID_PERSON INT(9) NOT NULL,
    ID_CONTACT INT(9) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
--

--
-- SEQUENCE: SEQ_POC_SPRING_CASCADE_CONTACT
--
CREATE SEQUENCE DEV_POC_SPRING_CASCADE_DATABASE.SEQ_POC_SPRING_CASCADE_REL_PERSON_CONTACT
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
NOCACHE
--  NOORDER
;

--
-- TABLE: POC_SPRING_CASCADE_SYSTEM_VALUE
--
CREATE TABLE DEV_POC_SPRING_CASCADE_DATABASE.POC_SPRING_CASCADE_SYSTEM_VALUE
(
    ID_SYSTEM_VALUE INT(9) auto_increment primary key NOT NULL,
    ID_SYSTEM_VALUE_TYPE INT(9) not null,
    DESCRIPTION_SYSTEM_VALUE VARCHAR(255) NOT NULL,
    CODE_SYSTEM_VALUE VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- SEQUENCE: SEQ_POC_SPRING_CASCADE_SYSTEM_VALUE
--
CREATE SEQUENCE DEV_POC_SPRING_CASCADE_DATABASE.SEQ_POC_SPRING_CASCADE_SYSTEM_VALUE
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
NOCACHE
--  NOORDER
;

CREATE TABLE DEV_POC_SPRING_CASCADE_DATABASE.POC_SPRING_CASCADE_SYSTEM_VALUE_TYPE
(
    ID_SYSTEM_VALUE_TYPE INT(9) auto_increment primary key NOT NULL,
    DESCRIPTION_SYSTEM_VALUE_TYPE VARCHAR(255) NOT NULL,
    CODE_SYSTEM_VALUE_TYPE VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- SEQUENCE: SEQ_POC_SPRING_CASCADE_SYSTEM_VALUE
--
CREATE SEQUENCE DEV_POC_SPRING_CASCADE_DATABASE.SEQ_POC_SPRING_CASCADE_SYSTEM_VALUE_TYPE
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
NOCACHE
--  NOORDER
;

--
-- TABLE: POC_SPRING_CASCADE_USER
--
CREATE TABLE DEV_POC_SPRING_CASCADE_DATABASE.POC_SPRING_CASCADE_USER
(
    ID_USER INT(9) auto_increment primary key NOT NULL,
    ID_PERSON INT(9),
    LOGIN_USER VARCHAR(255) NOT NULL,
    PASSWORD_USER VARCHAR(255) NOT null,
    foreign key (ID_PERSON)
    	references poc_spring_cascade_person(ID_PERSON)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- SEQUENCE: SEQ_POC_SPRING_CASCADE_USER
--
CREATE SEQUENCE DEV_POC_SPRING_CASCADE_DATABASE.SEQ_POC_SPRING_CASCADE_USER
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
NOCACHE
--  NOORDER
;
